# Use an official Node.js runtime as the base image
FROM node:23.11-alpine AS base

# Set working directory
WORKDIR /app

# Copy package.json and yarn.lock
COPY frontend/package.json frontend/yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the application code
COPY frontend/ .

FROM base as development

EXPOSE 5173

CMD ["yarn", "run", "dev"]
